### PR TITLE
SK project Update

### PR DESCRIPTION
**Pull request by Pysk369**
Sukhbir Kaur

### CODE REVIEW

**Comment by leej3** [comment]
From doc, this is more appropriate place:
1. Project idea: I have microarray and RNA sequencing data in excel. I would like to create  sheet formulas which can combine together and can sort easily;  how much they are altered in the same or opposite/ direction between two samples .& How many transcripts are similar in both platforms.
 2. If this project idea (1) is over ambitious at this level, I would like to create a simple  freezer inventory for our lab which can facilitate finding reagents easily with  search engines.  I have created a test design in my project at github with normal text.

**Comment by Pysk369** [comment]
Thanks
Sukhbir

Sent from my iPhone

On Apr 23, 2020, at 6:44 PM, john lee <notifications@github.com> wrote:

﻿

From doc, this is more appropriate place:

  1.  Project idea: I have microarray and RNA sequencing data in excel. I would like to create sheet formulas which can combine together and can sort easily; how much they are altered in the same or opposite/ direction between two samples .& How many transcripts are similar in both platforms.
  2.  If this project idea (1) is over ambitious at this level, I would like to create a simple freezer inventory for our lab which can facilitate finding reagents easily with search engines. I have created a test design in my project at github with normal text.

**Comment by Pysk369** [comment]
Hi, I am trying to update my Jupyter notebook  into my, 'project_spring_2020/pull/22' at Github.   Please let me know how I can add updated file.
Thanks
Sukhbir

**Comment by leej3** [comment]
At this point you should likely be adding .py files. The notebook is fine for showing progress but most of the marks are awarded for a well organized python package.

For git usage you should have a look through the course notebook for the week on using git. A brief summary is:

```
git add my_notebook.ipynb
git commit -m 'add functionality for X to notebook'
git push
```

**Comment by Pysk369** [comment]
Thanks
Sukhbir

Sent from my iPhone

On May 5, 2020, at 2:32 PM, john lee <notifications@github.com> wrote:

﻿

At this point you should likely be adding .py files. The notebook is fine for showing progress but most of the marks are awarded for a well organized python package.

For git usage you should have a look through the course notebook for the week on using git. A brief summary is:

git add my_notebook.ipynb
git commit -m 'add functionality for X to notebook'
git push

**Comment by leej3** [comment]
``` 
According to your suggestion, I  actually figured out my project using Panda
and matlibplot how to load excel files, compare and merge the data, . I
attempted to perform analysis  with some code.  I would like to have feedback
about the pandas command that I used  at
https://github.com/Pysk369/project_spring_2020.Only issue left is to add a
file to an updated notebook in the github project. I have added project files
in the format of  .py and .md as zip via upload creating fork branches. At
this point, I got confused with updates in github.

```
Posting here...

**Comment by leej3** [comment]
+ Make functions out of the code.
+ Add docstrings to the functions
+ Take relevant code out of notebook and put it in .py files
+ Add a setup.py
+ Move the .py file into the subdirectory named in the setup.py file to make it a package
+ Add a file called `__init__.py` to the subdirectory

**Comment by leej3** [comment]
example function:

```
def my_plot():
    """
    This function plots two time series
    """
    my_series_1 = pd.Series([4, 6, 2,10, -4, -20, -3, 40])
    my_series_2 = pd.Series([14, 16, 12,10, -14, -20, -13, 40])
    
    plt.scatter([my_series_1],[my_series_2])
    plt.show()
```

**Comment by Pysk369** [comment]
Thanks
Sukhbir

Sent from my iPhone

On May 7, 2020, at 8:01 PM, john lee <notifications@github.com> wrote:

﻿

example function:

def my_plot():
    """
    This function plots two time series
    """
    my_series_1 = pd.Series([4, 6, 2,10, -4, -20, -3, 40])
    my_series_2 = pd.Series([14, 16, 12,10, -14, -20, -13, 40])

    plt.scatter([my_series_1],[my_series_2])
    plt.show()

**Pull request closed without merging**
